# Generated by Django 5.0.9 on 2026-09-16 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(default='📍', help_text="Un emoji utilisé comme icône dans l'interface.", max_length=10, verbose_name='Icône (emoji)')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Identifie le visiteur non authentifié (MVP sans compte obligatoire).', max_length=64, verbose_name='Clé de session')),
                ('title', models.CharField(default='Mon itinéraire CamWay', max_length=200, verbose_name='Titre')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Durée (jours)')),
                ('budget_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget indicatif (FCFA)')),
                ('interests', models.CharField(blank=True, max_length=300, verbose_name="Centres d'intérêt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('organisation', models.CharField(blank=True, help_text='Ex : MINTOUL, Collectivité territoriale, Office de tourisme...', max_length=200, verbose_name='Organisme')),
                ('url', models.URLField(blank=True, verbose_name='URL / référence documentaire')),
                ('source_type', models.CharField(choices=[('officielle', 'Source officielle'), ('secondaire', 'Source secondaire fiable')], default='secondaire', max_length=20, verbose_name='Type de source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Département')),
                ('commune', models.CharField(blank=True, max_length=120, verbose_name='Commune / Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('activities', models.TextField(blank=True, help_text='Une activité par ligne.', verbose_name='Activités')),
                ('accessibility', models.TextField(blank=True, verbose_name="Conditions d'accès")),
                ('nearby_services', models.TextField(blank=True, verbose_name='Services à proximité')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='Horaires')),
                ('price_information', models.CharField(blank=True, help_text="Ne renseigner que si l'information est fiable (§8.4).", max_length=200, verbose_name='Information tarifaire')),
                ('image_url', models.URLField(blank=True, verbose_name='Image (URL)')),
                ('estimated_budget_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget indicatif (FCFA / personne)')),
                ('recommended_duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de visite conseillée (heures)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon (non publié)'), ('to_verify', 'À vérifier'), ('published', 'Publié'), ('archived', 'Archivé')], default='to_verify', max_length=20, verbose_name='Statut')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Date de vérification')),
                ('confidence_level', models.CharField(choices=[('eleve', 'Élevé (source officielle vérifiée)'), ('moyen', 'Moyen (source secondaire fiable)'), ('faible', 'Faible (à vérifier)'), ('non_verifie', 'Non vérifié')], default='non_verifie', max_length=20, verbose_name='Niveau de confiance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tourism.category', verbose_name='Catégorie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tourism.region', verbose_name='Région')),
                ('sources', models.ManyToManyField(blank=True, related_name='sites', to='tourism.source', verbose_name='Sources')),
            ],
            options={
                'verbose_name': 'Fiche touristique',
                'verbose_name_plural': 'Fiches touristiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Visiteur'), ('assistant', 'CamWay')], max_length=10, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tourism.conversation', verbose_name='Conversation')),
                ('referenced_sites', models.ManyToManyField(blank=True, related_name='messages', to='tourism.touristsite', verbose_name='Sites référencés')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='Jour')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tourism.itinerary', verbose_name='Itinéraire')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='tourism.touristsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': "Étape d'itinéraire",
                'verbose_name_plural': "Étapes d'itinéraire",
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(max_length=150, verbose_name='Vérifié par')),
                ('verification_date', models.DateField(verbose_name='Date de vérification')),
                ('confidence_level', models.CharField(choices=[('eleve', 'Élevé (source officielle vérifiée)'), ('moyen', 'Moyen (source secondaire fiable)'), ('faible', 'Faible (à vérifier)'), ('non_verifie', 'Non vérifié')], max_length=20, verbose_name='Niveau de confiance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='tourism.touristsite', verbose_name='Fiche')),
            ],
            options={
                'verbose_name': 'Enregistrement de vérification',
                'verbose_name_plural': 'Enregistrements de vérification',
                'ordering': ['-verification_date'],
            },
        ),
    ]
