# Generated by Django 5.0.9 on 2026-09-16 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement si le visiteur s'est connecté (fonctionnalité hors MVP, §6.2).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL, verbose_name='Compte visiteur'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('participants', models.PositiveIntegerField(default=1, verbose_name='Nombre de participants')),
                ('message', models.TextField(blank=True, verbose_name='Message / précisions')),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('contacted', 'Visiteur contacté'), ('confirmed', 'Confirmée par le prestataire'), ('declined', 'Déclinée / indisponible')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='tourism.touristsite', verbose_name='Site concerné')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to=settings.AUTH_USER_MODEL, verbose_name='Compte visiteur')),
            ],
            options={
                'verbose_name': 'Demande de réservation',
                'verbose_name_plural': 'Demandes de réservation (hors MVP)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fcfa', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('provider', models.CharField(choices=[('not_connected', 'Aucun prestataire réel connecté'), ('demo', 'Simulation locale (mode démonstration, aucun débit réel)')], default='not_connected', max_length=20, verbose_name='Prestataire de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('demo_confirmed', 'Confirmé en mode démonstration (non réel)'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tourism.bookingrequest', verbose_name='Demande associée')),
            ],
            options={
                'verbose_name': 'Paiement (architecture, hors MVP)',
                'verbose_name_plural': 'Paiements (architecture, hors MVP)',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('provider_type', models.CharField(choices=[('guide', 'Guide touristique'), ('agence', 'Agence de voyage'), ('hebergement', 'Hébergement'), ('activite', "Prestataire d'activités")], max_length=20, verbose_name='Type de prestataire')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('status', models.CharField(choices=[('draft', 'Brouillon (non publié)'), ('to_verify', 'À vérifier'), ('published', 'Publié'), ('archived', 'Archivé')], default='to_verify', max_length=20, verbose_name='Statut')),
                ('confidence_level', models.CharField(choices=[('eleve', 'Élevé (source officielle vérifiée)'), ('moyen', 'Moyen (source secondaire fiable)'), ('faible', 'Faible (à vérifier)'), ('non_verifie', 'Non vérifié')], default='non_verifie', max_length=20, verbose_name='Niveau de confiance')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Date de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='tourism.region', verbose_name="Région d'intervention")),
                ('sites', models.ManyToManyField(blank=True, related_name='providers', to='tourism.touristsite', verbose_name='Sites concernés')),
                ('sources', models.ManyToManyField(blank=True, related_name='providers', to='tourism.source', verbose_name='Sources')),
            ],
            options={
                'verbose_name': 'Prestataire vérifié',
                'verbose_name_plural': 'Prestataires vérifiés (réseau touristique V2)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='tourism.provider', verbose_name='Prestataire sollicité'),
        ),
    ]
