# Generated by Django 5.0.9 on 2026-09-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_itinerary_user_bookingrequest_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='indigenous_people',
            field=models.CharField(blank=True, help_text='Ex : Bakweri, Bamoun, Baka... — information générale sur le peuplement de la zone, à recouper avec une source.', max_length=200, verbose_name='Peuple(s) autochtone(s) de la zone'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='local_language',
            field=models.CharField(blank=True, help_text='Ex : Mokpe, Shüpamem, Fulfulde... en plus du français/anglais, langues officielles.', max_length=200, verbose_name='Langue(s) locale(s) parlée(s)'),
        ),
    ]
