# Generated by Django 5.0.9 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_touristsite_indigenous_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-location-dot', help_text='Ex : fa-solid fa-leaf. Voir fontawesome.com/icons pour la liste complète.', max_length=40, verbose_name='Icône (classe Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('not_connected', 'Aucun prestataire réel connecté')], default='not_connected', max_length=20, verbose_name='Prestataire de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
