# Generated by Django 5.0.9 on 2026-09-17 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_payment_options_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='video_caption',
            field=models.CharField(blank=True, help_text='Ex. « Visite de vérification sur site, mars 2026 » — apparaît sous la vidéo.', max_length=200, verbose_name='Légende de la vidéo'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='video_file',
            field=models.FileField(blank=True, help_text="Vidéo hébergée directement par CamWay (ex. vidéo de vérification du site sur le terrain), lisible sans dépendre d'un service tiers ni d'une clé API externe. Formats conseillés : MP4 (H.264), quelques dizaines de Mo maximum.", null=True, upload_to='sites/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov'])], verbose_name='Vidéo (fichier)'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='video_url',
            field=models.URLField(blank=True, help_text="Alternative au fichier ci-dessus : lien vers une vidéo déjà hébergée ailleurs (YouTube, Vimeo, site institutionnel...). Un simple lien public suffit — aucune clé d'API n'est nécessaire, la vidéo s'intègre ou s'ouvre automatiquement. Si les deux champs sont renseignés, le fichier ci-dessus est prioritaire.", verbose_name='Vidéo (lien externe)'),
        ),
    ]
