"""
Django settings for camway project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# ---------------------------------------------------------------------------
# Sécurité de base
# ---------------------------------------------------------------------------
# IMPORTANT pour une mise en production (ministère ou tout autre usage
# public) : DJANGO_DEBUG doit être explicitement mis à "0" dans .env, et
# DJANGO_SECRET_KEY doit être une valeur secrète générée pour cet
# environnement (jamais la valeur de secours ci-dessous, qui n'existe que
# pour permettre à `manage.py check` / au développement local de tourner
# sans configuration préalable).
DEBUG = _env_bool("DJANGO_DEBUG", True)

_INSECURE_DEV_KEY = "django-insecure-end59)37%p3lo!qf70@g+$ah1*kvd5$w-e--m*4=79hl2*u(er"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or _INSECURE_DEV_KEY

if not DEBUG and SECRET_KEY == _INSECURE_DEV_KEY:
    raise RuntimeError(
        "DJANGO_DEBUG=0 (production) mais DJANGO_SECRET_KEY n'est pas défini dans .env. "
        "Générez une clé secrète dédiée (ex. `python -c \"import secrets; print(secrets.token_urlsafe(50))\"`) "
        "et renseignez-la avant de démarrer le serveur en production."
    )

# ALLOWED_HOSTS : en développement (DEBUG=1), on autorise tout pour ne pas
# gêner les tests locaux. En production (DEBUG=0), la liste doit être
# fournie explicitement via DJANGO_ALLOWED_HOSTS (domaines séparés par des
# virgules, ex. "camway.mintoul.gov.cm,www.camway.mintoul.gov.cm").
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    raise RuntimeError(
        "DJANGO_DEBUG=0 (production) mais DJANGO_ALLOWED_HOSTS n'est pas défini dans .env. "
        "Renseignez-y le(s) nom(s) de domaine réel(s) du site, ex. "
        "DJANGO_ALLOWED_HOSTS=camway.mintoul.gov.cm"
    )

_csrf_trusted_env = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_env.split(",") if o.strip()]

# --- Intégrations configurées via .env (voir les commentaires de ce fichier) ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash").strip()
GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "").strip()

# ---------------------------------------------------------------------------
# En-têtes et cookies de sécurité — appliqués uniquement hors DEBUG, pour ne
# pas gêner le développement local en HTTP simple. En production, le site
# DOIT être servi en HTTPS (obligatoire pour un site institutionnel).
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"
    # Si le site est déployé derrière un proxy/reverse-proxy HTTPS
    # (Render, Railway, nginx...) — ce qui est le cas ici vu la présence
    # d'un Procfile gunicorn — la connexion entre le proxy et Django est
    # en clair (http) même si le visiteur est bien en https. Sans cette
    # ligne, Django croit systématiquement que la requête N'EST PAS
    # sécurisée : SESSION_COOKIE_SECURE / CSRF_COOKIE_SECURE font alors
    # rejeter les cookies (session, csrftoken) par le navigateur, la
    # session ne survit plus d'une requête à l'autre, et chaque page vue
    # démarre une conversation vide : le message envoyé dans le dialogue
    # (F2) et la réponse générée semblent alors ne jamais apparaître.
    # Ne l'activez que si un proxy de confiance positionne bien
    # X-Forwarded-Proto (Render/Railway le font par défaut) ; sinon
    # laissez DJANGO_BEHIND_PROXY=0 dans .env.
    if _env_bool("DJANGO_BEHIND_PROXY", True):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Django a besoin de lire ce cookie côté JS pour certains formulaires AJAX ; le CSRF token reste vérifié côté serveur.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "camway": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tourism',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'camway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tourism.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'camway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# SQLite par défaut (développement / démo). Pour la production, définissez
# DATABASE_URL dans .env (ex. postgres://user:password@host:5432/camway) :
# Postgres est recommandé pour un usage institutionnel multi-utilisateurs
# (SQLite ne gère pas bien les écritures concurrentes à volume élevé).

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=not DEBUG)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'tourism:account'
LOGOUT_REDIRECT_URL = 'tourism:home'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Sert les fichiers statiques compressés et versionnés directement
        # par l'application (WhiteNoise), sans dépendre d'un serveur web
        # externe pour les servir en production.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
